tanh_controller:
  ros__parameters:
    topics:
      vehicle_odometry: /fmu/out/vehicle_odometry
      trajectory_setpoint: /tanh_controller/trajectory_setpoint
      actuator_motors: /fmu/in/actuator_motors
      offboard_control_mode: /fmu/in/offboard_control_mode
      vehicle_command: /fmu/in/vehicle_command

    control_rate_hz: 100.0
    publish_offboard_control_mode: true
    auto_offboard: true
    auto_arm: true
    offboard_warmup: 10

    model:
      mass: 2.0643076923076915
      gravity: 9.81
      inertia_diag: [0.02384669, 0.02394962, 0.04399995]

    position:
      M1: [1.0, 1.0, 1.0]
      K1: [1.5, 1.5, 1.5]
      M2: [3.0, 3.0, 3.0]
      K2: [1.0, 1.0, 1.0]
      max_tilt_deg: 35.0
      observer:
        Pv: [0.0, 0.0, 0.0]
        Lv: [5.0, 5.0, 5.0]

    attitude:
      M_theta: [3.0, 3.0, 3.0]
      K_theta: [4.0, 4.0, 4.0]
      M_omega: [20.0, 20.0, 15.0]
      K_omega: [2.0, 2.0, 2.0]
      observer:
        P_omega: [0.0, 0.0, 0.0]
        L_omega: [5.0, 5.0, 5.0]

    allocation:
      l: 0.246073
      beta: 0.78539816339
      cq_ct: 0.016

    motor:
      force_max: 8.54858
      output_map: [1, 3, 0, 2]   # 输出索引0..3 <- 内部索引(默认G1列)：[前左, 前右, 后右, 后左]
