tanh_controller:
  ros__parameters:
    topics:
      vehicle_odometry: /fmu/out/vehicle_odometry
      trajectory_setpoint: /tanh_controller/trajectory_setpoint
      actuator_motors: /fmu/in/actuator_motors
      offboard_control_mode: /fmu/in/offboard_control_mode
      vehicle_command: /fmu/in/vehicle_command
      vehicle_thrust_setpoint: /fmu/in/vehicle_thrust_setpoint

    control_rate_hz: 2000.0
    publish_offboard_control_mode: true
    publish_vehicle_thrust_setpoint: true
    auto_offboard: true
    auto_arm: true
    offboard_warmup: 10

    model:
      mass: 2.0643076923076915
      gravity: 9.81
      inertia_diag: [0.02384669, 0.02394962, 0.04399995]

    position:
      M1: [2.0, 2.0, 2.0]
      K1: [0.5, 0.5, 5.0]
      M2: [6.0, 6.0, 6.0]
      K2: [1.0, 1.0, 1.0]
      max_tilt_deg: 35.0
      observer:
        Pv: [0.1, 0.1, 0.1]
        Lv: [1.0, 1.0, 1.0]

    attitude:
      M_theta: [2.0, 2.0, 2.0]
      K_theta: [5.0, 5.0, 5.0]
      M_omega: [25.0, 25.0, 10.0]
      K_omega: [1.2, 1.2, 1.0]
      observer:
        P_omega: [0.1, 0.1, 0.1]
        L_omega: [1.0, 1.0, 1.0]

    allocation:
      l: 0.246073
      beta: 0.78539816339
      cq_ct: 0.016

    motor:
      force_max: 8.54858
      output_map: [1, 3, 0, 2]   # 输出索引0..3 <- 内部索引(默认G1列)：[前左, 前右, 后右, 后左]
